# Hugging face

Explore datasets from hugging face for add metadata to the song

In [74]:
import pandas as pd

In [75]:
df_maharshipandya = pd.read_csv("hf://datasets/maharshipandya/spotify-tracks-dataset/dataset.csv")
df_maharshipandya.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [76]:
df_khepplewhite = pd.read_csv("hf://datasets/khepplewhite/SpotifyData/final.csv")
df_khepplewhite.head()

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,acousticness,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot
0,29477,spotify:track:4ZtFanR9U6ndgddUvNcjcG,1,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.335,0.000000,0.0849,0.6880,166.928,178147,Australia,Oceania,English,0
1,29478,spotify:track:6HU7h9RYOaPRFeh0R3UeAr,3,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.584,0.000006,0.3700,0.1780,180.917,215507,Australia,Oceania,English,0
2,29479,spotify:track:5CZ40GBx1sQ9agT82CLQCT,4,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.691,0.000000,0.1200,0.0849,100.607,229227,Australia,Oceania,English,0
3,29480,spotify:track:5wANPM4fQCJwkGd4rN57mH,6,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.768,0.000014,0.1060,0.1370,143.875,242013,Australia,Oceania,English,0
4,29481,spotify:track:5JCoSi02qi3jJeHdZXMmR8,7,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.866,0.000000,0.1470,0.2180,172.929,152667,Australia,Oceania,English,0

In [77]:
maharshipandya_columns = df_maharshipandya.columns
maharshipandya_columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [78]:
khepplewhite_columns = df_khepplewhite.columns
khepplewhite_columns

Index(['Unnamed: 0', 'uri', 'rank', 'artist_names', 'artists_num',
       'artist_individual', 'artist_id', 'artist_genre', 'artist_img',
       'collab', 'track_name', 'release_date', 'album_num_tracks',
       'album_cover', 'source', 'peak_rank', 'previous_rank', 'weeks_on_chart',
       'streams', 'week', 'danceability', 'energy', 'key', 'mode', 'loudness',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration', 'country', 'region', 'language',
       'pivot'],
      dtype='object')

## Unify colums for each data frame

In [79]:
# Get commons columns from both datasets in a set
common_columns = set(df_maharshipandya.columns).intersection(set(df_khepplewhite.columns))
common_columns

{'Unnamed: 0',
 'acousticness',
 'danceability',
 'energy',
 'instrumentalness',
 'key',
 'liveness',
 'loudness',
 'mode',
 'speechiness',
 'tempo',
 'track_name',
 'valence'}

In [80]:
common_columns.remove("Unnamed: 0")
common_columns

{'acousticness',
 'danceability',
 'energy',
 'instrumentalness',
 'key',
 'liveness',
 'loudness',
 'mode',
 'speechiness',
 'tempo',
 'track_name',
 'valence'}

- Investigate track_id

In [81]:
df_maharshipandya["track_id"]

0         5SuOikwiRyPMVoIQDJUgSV
1         4qPNDBW1i3p13qLCt0Ki3A
2         1iJBSr7s7jYXzM8EGcbK5b
3         6lfxq3CG4xtTiEg7opyCyx
4         5vjLSffimiIP26QG5WcN2K
                   ...
113995    2C3TZjDRiAzdyViavDJ217
113996    1hIz5L4IB9hN3WRYPOCGPw
113997    6x8ZfSoqDjuNa5SVP5QjvX
113998    2e6sXL2bYv4bSz6VTdnfLs
113999    2hETkH7cOfqmz3LqZDHZf5
Name: track_id, Length: 114000, dtype: object

In [82]:
df_khepplewhite["uri"]

0        spotify:track:4ZtFanR9U6ndgddUvNcjcG
1        spotify:track:6HU7h9RYOaPRFeh0R3UeAr
2        spotify:track:5CZ40GBx1sQ9agT82CLQCT
3        spotify:track:5wANPM4fQCJwkGd4rN57mH
4        spotify:track:5JCoSi02qi3jJeHdZXMmR8
                         ...
66169    spotify:track:4cG7HUWYHBV6R6tHn1gxrl
66170    spotify:track:4cG7HUWYHBV6R6tHn1gxrl
66171    spotify:track:2g6tReTlM2Akp41g0HaeXN
66172    spotify:track:2g6tReTlM2Akp41g0HaeXN
66173    spotify:track:2g6tReTlM2Akp41g0HaeXN
Name: uri, Length: 66174, dtype: object

In [83]:
df_khepplewhite["track_id"] = df_khepplewhite["uri"].str.split(":").str[-1]
df_khepplewhite.head()

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot,track_id
0,29477,spotify:track:4ZtFanR9U6ndgddUvNcjcG,1,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.000000,0.0849,0.6880,166.928,178147,Australia,Oceania,English,0,4ZtFanR9U6ndgddUvNcjcG
1,29478,spotify:track:6HU7h9RYOaPRFeh0R3UeAr,3,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.000006,0.3700,0.1780,180.917,215507,Australia,Oceania,English,0,6HU7h9RYOaPRFeh0R3UeAr
2,29479,spotify:track:5CZ40GBx1sQ9agT82CLQCT,4,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.000000,0.1200,0.0849,100.607,229227,Australia,Oceania,English,0,5CZ40GBx1sQ9agT82CLQCT
3,29480,spotify:track:5wANPM4fQCJwkGd4rN57mH,6,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.000014,0.1060,0.1370,143.875,242013,Australia,Oceania,English,0,5wANPM4fQCJwkGd4rN57mH
4,29481,spotify:track:5JCoSi02qi3jJeHdZXMmR8,7,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.000000,0.1470,0.2180,172.929,152667,Australia,Oceania,English,0,5JCoSi02qi3jJeHdZXMmR8

- Artists

In [84]:
def refactor_artists_namees(artists_names: str) -> str:
    split_names = artists_names.split(", ")

    
    # Unify with ;
    return ";".join(split_names)

In [85]:
df_khepplewhite["artists"] = df_khepplewhite["artist_names"].apply(refactor_artists_namees)
df_khepplewhite.head()

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,liveness,valence,tempo,duration,country,region,language,pivot,track_id,artists
0,29477,spotify:track:4ZtFanR9U6ndgddUvNcjcG,1,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.0849,0.6880,166.928,178147,Australia,Oceania,English,0,4ZtFanR9U6ndgddUvNcjcG,Olivia Rodrigo
1,29478,spotify:track:6HU7h9RYOaPRFeh0R3UeAr,3,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.3700,0.1780,180.917,215507,Australia,Oceania,English,0,6HU7h9RYOaPRFeh0R3UeAr,Olivia Rodrigo
2,29479,spotify:track:5CZ40GBx1sQ9agT82CLQCT,4,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.1200,0.0849,100.607,229227,Australia,Oceania,English,0,5CZ40GBx1sQ9agT82CLQCT,Olivia Rodrigo
3,29480,spotify:track:5wANPM4fQCJwkGd4rN57mH,6,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.1060,0.1370,143.875,242013,Australia,Oceania,English,0,5wANPM4fQCJwkGd4rN57mH,Olivia Rodrigo
4,29481,spotify:track:5JCoSi02qi3jJeHdZXMmR8,7,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.1470,0.2180,172.929,152667,Australia,Oceania,English,0,5JCoSi02qi3jJeHdZXMmR8,Olivia Rodrigo

In [86]:
df_khepplewhite.head(-1)

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,liveness,valence,tempo,duration,country,region,language,pivot,track_id,artists
0,29477,spotify:track:4ZtFanR9U6ndgddUvNcjcG,1,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.0849,0.6880,166.928,178147,Australia,Oceania,English,0,4ZtFanR9U6ndgddUvNcjcG,Olivia Rodrigo
1,29478,spotify:track:6HU7h9RYOaPRFeh0R3UeAr,3,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.3700,0.1780,180.917,215507,Australia,Oceania,English,0,6HU7h9RYOaPRFeh0R3UeAr,Olivia Rodrigo
2,29479,spotify:track:5CZ40GBx1sQ9agT82CLQCT,4,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.1200,0.0849,100.607,229227,Australia,Oceania,English,0,5CZ40GBx1sQ9agT82CLQCT,Olivia Rodrigo
3,29480,spotify:track:5wANPM4fQCJwkGd4rN57mH,6,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.1060,0.1370,143.875,242013,Australia,Oceania,English,0,5wANPM4fQCJwkGd4rN57mH,Olivia Rodrigo
4,29481,spotify:track:5JCoSi02qi3jJeHdZXMmR8,7,Olivia Rodrigo,1,Olivia Rodrigo,spotify:artist:1McMsnEElThX1knmY4oliG,pop,https://i.scdn.co/image/ab6761610000e5ebee954a...,0,...,0.1470,0.2180,172.929,152667,Australia,Oceania,English,0,5JCoSi02qi3jJeHdZXMmR8,Olivia Rodrigo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66168,887167,spotify:track:4cG7HUWYHBV6R6tHn1gxrl,194,"Riton, Nightcrawlers, Mufasa & Hypeman, Dopamine",4,Nightcrawlers,spotify:artist:1gALaWbNDnwS2ECV09sn2A,hip house,https://i.scdn.co/image/ab6761610000e5eb512e2f...,1,...,0.3030,0.8010,122.980,169153,Ireland,Europe,English,1,4cG7HUWYHBV6R6tHn1gxrl,Riton;Nightcrawlers;Mufasa & Hypeman;Dopamine
66169,887168,spotify:track:4cG7HUWYHBV6R6tHn1gxrl,194,"Riton, Nightcrawlers, Mufasa & Hypeman, Dopamine",4,Mufasa & Hypeman,spotify:artist:4L2dV3zY7RmkeiNO035Fi0,tropical house,https://i.scdn.co/image/ab6761610000e5eb068e53...,1,...,0.3030,0.8010,122.980,169153,Ireland,Europe,English,1,4cG7HUWYHBV6R6tHn1gxrl,Riton;Nightcrawlers;Mufasa & Hypeman;Dopamine
66170,887169,spotify:track:4cG7HUWYHBV6R6tHn1gxrl,194,"Riton, Nightcrawlers, Mufasa & Hypeman, Dopamine",4,Dopamine,spotify:artist:3Edve4VIATi0OZngclQlkN,0,https://i.scdn.co/image/ab6761610000e5eb09045f...,1,...,0.3030,0.8010,122.980,169153,Ireland,Europe,English,1,4cG7HUWYHBV6R6tHn1gxrl,Riton;Nightcrawlers;Mufasa & Hypeman;Dopamine
66171,887170,spotify:track:2g6tReTlM2Akp41g0HaeXN,195,"Kendrick Lamar, Blxst, Amanda Reifer",3,Kendrick Lamar,spotify:artist:2YZyLoL8N0Wb9xBt1NhZWg,rap,https://i.scdn.co/image/ab6761610000e5eb437b9e...,1,...,0.1270,0.3620,100.988,239027,Ireland,Europe,English,0,2g6tReTlM2Akp41g0HaeXN,Kendrick Lamar;Blxst;Amanda Reifer
66172,887171,spotify:track:2g6tReTlM2Akp41g0HaeXN,195,"Kendrick Lamar, Blxst, Amanda Reifer",3,Blxst,spotify:artist:4qXC0i02bSFstECuXP2ZpL,pop rap,https://i.scdn.co/image/ab6761610000e5eb79ffd3...,1,...,0.1270,0.3620,100.988,239027,Ireland,Europe,English,1,2g6tReTlM2Akp41g0HaeXN,Kendrick Lamar;Blxst;Amanda Reifer

In [87]:
print(df_maharshipandya.columns)
print(df_khepplewhite.columns)

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')
Index(['Unnamed: 0', 'uri', 'rank', 'artist_names', 'artists_num',
       'artist_individual', 'artist_id', 'artist_genre', 'artist_img',
       'collab', 'track_name', 'release_date', 'album_num_tracks',
       'album_cover', 'source', 'peak_rank', 'previous_rank', 'weeks_on_chart',
       'streams', 'week', 'danceability', 'energy', 'key', 'mode', 'loudness',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration', 'country', 'region', 'language',
       'pivot', 'track_id', 'artists'],
      dtype='object')

In [88]:
common_columns.add("track_id")
common_columns.add("artists")
common_columns

{'acousticness',
 'artists',
 'danceability',
 'energy',
 'instrumentalness',
 'key',
 'liveness',
 'loudness',
 'mode',
 'speechiness',
 'tempo',
 'track_id',
 'track_name',
 'valence'}

In [89]:
colums_for_maharshipandya = common_columns.copy()
colums_for_maharshipandya.add("duration_ms")
colums_for_maharshipandya.add("explicit")
colums_for_maharshipandya.add("track_genre")
colums_for_maharshipandya

{'acousticness',
 'artists',
 'danceability',
 'duration_ms',
 'energy',
 'explicit',
 'instrumentalness',
 'key',
 'liveness',
 'loudness',
 'mode',
 'speechiness',
 'tempo',
 'track_genre',
 'track_id',
 'track_name',
 'valence'}

In [90]:
df_maharshipandya_filtered = df_maharshipandya[list(colums_for_maharshipandya)]
df_maharshipandya_filtered

,liveness,speechiness,valence,acousticness,track_name,track_genre,mode,track_id,key,energy,instrumentalness,artists,tempo,duration_ms,loudness,danceability,explicit
0,0.3580,0.1430,0.7150,0.0322,Comedy,acoustic,0,5SuOikwiRyPMVoIQDJUgSV,1,0.4610,0.000001,Gen Hoshino,87.917,230666,-6.746,0.676,False
1,0.1010,0.0763,0.2670,0.9240,Ghost - Acoustic,acoustic,1,4qPNDBW1i3p13qLCt0Ki3A,1,0.1660,0.000006,Ben Woodward,77.489,149610,-17.235,0.420,False
2,0.1170,0.0557,0.1200,0.2100,To Begin Again,acoustic,1,1iJBSr7s7jYXzM8EGcbK5b,0,0.3590,0.000000,Ingrid Michaelson;ZAYN,76.332,210826,-9.734,0.438,False
3,0.1320,0.0363,0.1430,0.9050,Can't Help Falling In Love,acoustic,1,6lfxq3CG4xtTiEg7opyCyx,0,0.0596,0.000071,Kina Grannis,181.740,201933,-18.515,0.266,False
4,0.0829,0.0526,0.1670,0.4690,Hold On,acoustic,1,5vjLSffimiIP26QG5WcN2K,2,0.4430,0.000000,Chord Overstreet,119.949,198853,-9.681,0.618,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,0.0863,0.0422,0.0339,0.6400,Sleep My Little Boy,world-music,1,2C3TZjDRiAzdyViavDJ217,5,0.2350,0.928000,Rainy Lullaby,125.995,384999,-16.393,0.172,False
113996,0.1050,0.0401,0.0350,0.9940,Water Into Light,world-music,0,1hIz5L4IB9hN3WRYPOCGPw,0,0.1170,0.976000,Rainy Lullaby,85.239,385000,-18.318,0.174,False
113997,0.0839,0.0420,0.7430,0.8670,Miss Perfumado,world-music,0,6x8ZfSoqDjuNa5SVP5QjvX,0,0.3290,0.000000,Cesária Evora,132.378,271466,-10.895,0.629,False
113998,0.2700,0.0297,0.4130,0.3810,Friends,world-music,1,2e6sXL2bYv4bSz6VTdnfLs,7,0.5060,0.000000,Michael W. Smith,135.960,283893,-10.889,0.587,False
113999,0.0893,0.0725,0.7080,0.6810,Barbincor,world-music,0,2hETkH7cOfqmz3LqZDHZf5,1,0.4870,0.000000,Cesária Evora,79.198,241826,-10.204,0.526,False

In [91]:
columns_for_khepplewhite = common_columns.copy()
columns_for_khepplewhite.add("language")
columns_for_khepplewhite

{'acousticness',
 'artists',
 'danceability',
 'energy',
 'instrumentalness',
 'key',
 'language',
 'liveness',
 'loudness',
 'mode',
 'speechiness',
 'tempo',
 'track_id',
 'track_name',
 'valence'}

In [92]:
df_khepplewhite_filtered = df_khepplewhite[list(columns_for_khepplewhite)]
df_khepplewhite_filtered

,liveness,speechiness,valence,acousticness,language,track_name,mode,track_id,key,energy,instrumentalness,artists,tempo,loudness,danceability
0,0.0849,0.1540,0.6880,0.3350,English,good 4 u,1,4ZtFanR9U6ndgddUvNcjcG,9,0.664,0.000000,Olivia Rodrigo,166.928,-5.044,0.563
1,0.3700,0.1120,0.1780,0.5840,English,deja vu,1,6HU7h9RYOaPRFeh0R3UeAr,2,0.612,0.000006,Olivia Rodrigo,180.917,-7.222,0.442
2,0.1200,0.0338,0.0849,0.6910,English,traitor,1,5CZ40GBx1sQ9agT82CLQCT,3,0.339,0.000000,Olivia Rodrigo,100.607,-7.885,0.380
3,0.1060,0.0578,0.1370,0.7680,English,drivers license,1,5wANPM4fQCJwkGd4rN57mH,10,0.431,0.000014,Olivia Rodrigo,143.875,-8.810,0.561
4,0.1470,0.0364,0.2180,0.8660,English,favorite crime,1,5JCoSi02qi3jJeHdZXMmR8,9,0.272,0.000000,Olivia Rodrigo,172.929,-10.497,0.369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66169,0.3030,0.1260,0.8010,0.0076,English,Friday (feat. Mufasa & Hypeman) - Dopamine Re-...,1,4cG7HUWYHBV6R6tHn1gxrl,2,0.862,0.000132,Riton;Nightcrawlers;Mufasa & Hypeman;Dopamine,122.980,-3.424,0.824
66170,0.3030,0.1260,0.8010,0.0076,English,Friday (feat. Mufasa & Hypeman) - Dopamine Re-...,1,4cG7HUWYHBV6R6tHn1gxrl,2,0.862,0.000132,Riton;Nightcrawlers;Mufasa & Hypeman;Dopamine,122.980,-3.424,0.824
66171,0.1270,0.2470,0.3620,0.3190,English,Die Hard,0,2g6tReTlM2Akp41g0HaeXN,1,0.736,0.001160,Kendrick Lamar;Blxst;Amanda Reifer,100.988,-8.072,0.775
66172,0.1270,0.2470,0.3620,0.3190,English,Die Hard,0,2g6tReTlM2Akp41g0HaeXN,1,0.736,0.001160,Kendrick Lamar;Blxst;Amanda Reifer,100.988,-8.072,0.775
66173,0.1270,0.2470,0.3620,0.3190,English,Die Hard,0,2g6tReTlM2Akp41g0HaeXN,1,0.736,0.001160,Kendrick Lamar;Blxst;Amanda Reifer,100.988,-8.072,0.775

In [96]:
# get index for each dataframe
df_maharshipandya_filtered.index

Index(['5SuOikwiRyPMVoIQDJUgSV', '4qPNDBW1i3p13qLCt0Ki3A',
       '1iJBSr7s7jYXzM8EGcbK5b', '6lfxq3CG4xtTiEg7opyCyx',
       '5vjLSffimiIP26QG5WcN2K', '01MVOl9KtVTNfFiBU9I7dc',
       '6Vc5wAMmXdKIAM7WUoEb7N', '1EzrEOXmMH3G43AXT1y7pA',
       '0IktbUcnAGrvD03AWnz3Q8', '7k9GuJYLp2AzqokyEdwEw2',
       ...
       '2A4dSiJmbviL56CBupkh6C', '0CE0Y6GM75cbrqao8EOAlW',
       '3FjOBB4EyIXHYUtSgrIdY9', '4OkMK49i3NApR1KsAIsTf6',
       '4WbOUe6T0sozC7z5ZJgiAA', '2C3TZjDRiAzdyViavDJ217',
       '1hIz5L4IB9hN3WRYPOCGPw', '6x8ZfSoqDjuNa5SVP5QjvX',
       '2e6sXL2bYv4bSz6VTdnfLs', '2hETkH7cOfqmz3LqZDHZf5'],
      dtype='object', name='track_id', length=114000)

In [97]:
df_khepplewhite_filtered.index

Index(['4ZtFanR9U6ndgddUvNcjcG', '6HU7h9RYOaPRFeh0R3UeAr',
       '5CZ40GBx1sQ9agT82CLQCT', '5wANPM4fQCJwkGd4rN57mH',
       '5JCoSi02qi3jJeHdZXMmR8', '02MWAaffLxlfxAUY7c5dvx',
       '67BtfxlNbhBmCDR2L2l8qd', '0BGwAKW4u8kWOhWFflZxfl',
       '6SRsiMl7w1USE4mFqrOhHC', '2tGvwE8GcFKwNdAXMnlbfl',
       ...
       '1D2ZNECRd7KIlA4pyOUGsv', '1bgKMxPQU7JIZEhNsM1vFs',
       '1bgKMxPQU7JIZEhNsM1vFs', '4cG7HUWYHBV6R6tHn1gxrl',
       '4cG7HUWYHBV6R6tHn1gxrl', '4cG7HUWYHBV6R6tHn1gxrl',
       '4cG7HUWYHBV6R6tHn1gxrl', '2g6tReTlM2Akp41g0HaeXN',
       '2g6tReTlM2Akp41g0HaeXN', '2g6tReTlM2Akp41g0HaeXN'],
      dtype='object', name='track_id', length=66174)

In [ ]:
# Combine both dataframe using track_id as key

df_maharshipandya_filtered = df_maharshipandya_filtered.set_index('track_id')
df_khepplewhite_filtered = df_khepplewhite_filtered.set_index('track_id')

In [104]:
df_khepplewhite_filtered_unique_columns = list(set(df_khepplewhite_filtered.columns) - set(df_maharshipandya_filtered.columns))
df_khepplewhite_filtered_unique_columns

['language']

In [105]:
df_merged = pd.merge(
    df_maharshipandya_filtered,
    df_khepplewhite_filtered[df_khepplewhite_filtered_unique_columns],
    left_index=True,
    right_index=True,
    how='outer'
)

In [106]:
df_merged

,liveness,speechiness,valence,acousticness,track_name,track_genre,mode,key,energy,instrumentalness,artists,tempo,duration_ms,loudness,danceability,explicit,language
track_id,,,,,,,,,,,,,,,,,
0000vdREvCVMxbQTkS888c,0.1540,0.1990,0.432,0.075700,Lolly,german,0.0,8.0,0.37400,0.00301,Rill,104.042,160725.0,-9.844,0.910,True,NaN
000CC8EParg64OmTxVnZ0p,0.1170,0.0366,0.341,0.406000,It's All Coming Back To Me Now (Glee Cast Vers...,club,1.0,0.0,0.51600,0.00000,Glee Cast,178.174,322933.0,-7.361,0.269,False,NaN
000Iz0K615UepwSJ5z2RE5,0.1110,0.0462,0.108,0.001140,Böxig Leise - Pig & Dan Remix,minimal-techno,0.0,5.0,0.56000,0.18100,Paul Kalkbrenner;Pig&Dan,119.997,515360.0,-13.264,0.686,False,NaN
000RDCYioLteXcutOjeweY,0.0825,0.1900,0.839,0.058300,Teeje Week,hip-hop,1.0,0.0,0.77000,0.00000,Jordan Sandhu,161.721,190203.0,-3.537,0.679,False,NaN
000qpdoc97IMTBvF8gwcpy,0.0916,0.0291,0.234,0.000964,Tief,minimal-techno,0.0,6.0,0.43100,0.72000,Paul Kalkbrenner,129.971,331240.0,-13.606,0.519,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7zxHiMmVLt4LGWpOMqOpUh,0.1570,0.0324,0.672,0.698000,"Aethu Kari Raavilum - From ""Bangalore Days""",pop-film,0.0,7.0,0.38200,0.00143,Haricharan;Gopi Sundar,119.992,325156.0,-11.464,0.766,False,NaN
7zxpdh3EqMq2JCkOI0EqcG,0.0916,0.0587,0.510,0.996000,"Two Worlds (From ""Tarzan"")",disney,1.0,10.0,0.00879,0.95900,Piano Genie,82.694,109573.0,-32.266,0.529,False,NaN
7zyYmIdjqqiX6kLryb7QBx,0.1050,0.0372,0.291,0.728000,以後別做朋友,mandopop,1.0,3.0,0.36000,0.00000,Eric Chou,130.576,260573.0,-9.458,0.423,False,NaN
7zybSU9tFO9HNlwmGF7stc,0.0974,0.0397,0.150,0.268000,Sunset Drive,electronic,0.0,10.0,0.83400,0.93200,Stereoclip,125.004,234300.0,-11.430,0.649,False,NaN
7zz7iNGIWhmfFE7zlXkMma,0.3780,0.0897,0.204,0.000023,Grant Hart,power-pop,1.0,4.0,0.95700,0.00630,The Posies,172.932,144973.0,-6.887,0.263,False,NaN